% -------------------------------------------------------------------
%  Generated by MATLAB on 31-Mar-2026 16:30:38
%  MATLAB version: 24.2.0.2773142 (R2024b) Update 2
% -------------------------------------------------------------------
saveVarsMat = load('Results_Control_SEIR_Monteria.mat');

Results_Control_SEIR_Monteria = saveVarsMat.Results_Control_SEIR_Monteria; % <1x1 struct> too many elements at Results_Control_SEIR_Monteria.I_real

clear saveVarsMat;
